### ISSUE TITLE
Likely bug in Module override

### ISSUE THREAD

**Issue by soumith** [bshillingford/autobw.torch#3]
At this line: https://github.com/bshillingford/autobw.torch/blob/master/tape.lua#L70

I think you want to keep the input/output around so that when you replay the tape backwards, everything seems correct.

However, for nn Modules, the module always has a single self.output that it reuses on every forward.

So, in something like:

``` lua
sigm = nn.Sigmoid()
tape = autobw.Tape()
input = torch.randn(10)

tape:begin()
output = sigm:forward(input)
for i=1,10 do
   output = sigm:forwrad(output)
end
tape:stop()

tape:backward()
```

The outputs recorded by the tape are overriden, because they are just references to the underlying storage.

Instead, if you modified line 71: https://github.com/bshillingford/autobw.torch/blob/master/tape.lua#L71
to be:
self.tape[#self.tape+1] = { module=self_, input=input:clone(), output=output:clone() }

I think then you will be okay.

**Comment by bshillingford** [comment]
Yes, that's a caveat with the way I'm currently doing things. I expect the
user to generate as many weight-sharing instances of the module as they
need, because I don't want to allocate memory during the training process.

I do think that's a useful thing to add as optional "copy mode" behaviour,
I'll add that. As a way to warn the user when "copy mode" is off, I think
it's reasonable to enforce that forward is called at most once per
recording.
